#!/usr/bin/env perl

use strict;
use warnings;

my @spook_lines = (
    # emacs
    "\$400 million in gold bullion",
    "[Hello to all my fans in domestic surveillance]", "AK-47", "ammunition",
    "arrangements", "assassination", "BATF", "bomb", "Cheney", "CIA",
    "class struggle", "Clinton", "Cocaine", "colonel", "counter-intelligence",
    "cracking", "Croatian", "cryptographic", "Delta Force", "DES",
    "domestic disruption", "explosion", "FBI", "fissionable", "FSF",
    "Ft. Bragg", "Ft. Meade", "genetic", "Honduras", "jihad", "Kennedy",
    "KGB", "Khaddafi", "kibo", "Legion of Doom", "Liberals", "Marxist",
    "Mossad", "munitions", "Nazi", "NORAD", "Noriega", "North Korea", "NSA",
    "nuclear", "Ortega", "Panama", "Peking", "PLO", "plutonium", "Qaddafi",
    "quiche", "radar", "Rule Psix", "Saddam Hussein", "SDI", "SEAL Team 6",
    "security", "Semtex", "Serbian", "smuggle", "South Africa", "Soviet",
    "spy", "strategic", "supercomputer", "terrorist", "Treasury", "Uzi",
    "Waco, Texas", "World Trade Center",

    # hugs
    "9-11", "Al Jazeera", "Al Qaeda", "Arabs", "Arafat", "Ashcroft", "Bush",
    "Chemical Ali", "conspiracy", "Diebold", "Eggs", "Embedded Journalism",
    "Fallujah", "Free Masons", "GOP", "Grass Roots", "Hamas", "IndyMedia",
    "Israel", "Kerry", "Kill the president", "Libya", "Lockheed-Martin",
    "Muslim", "Palestine", "Patriot Act", "Punch-cards", "Republican",
    "Rocket Propelled Grenades", "Shiite", "Skull and Bones", "Terrorism",
    "Voter Fraud", "war profiteering",

    # blog
    "2.3 Oz. cocaine", "20755-6000", "Al Amn al-Askari", "anarchy", "ASPIC",
    "assasinate", "assassinate", "Bletchley Park", "Clandestine",
    "Compsec 97", "Computer Terrorism", "Counter Terrorism Security",
    "Counterterrorism", "DefCon V", "Defense Information Warfare",
    "Defensive Information", "eavesdropping", "echelon",
    "Electronic Surveillance", "Encryption", "Enemy of the State",
    "Espionage", "Europol", "Glock 26", "HALO", "HERF pipe-bomb",
    "Information Security", "Information Terrorism", "Information Warfare",
    "InfoSec", "Lebed", "MI6", "Military Intelligence", "nailbomb",
    "National Information Infrastructure", "Offensive Information",
    "Offensive Information Warfare", "Ortega Waco", "Privacy", "Rewson",
    "Roswell", "SAFE", "Satellite imagery", "Sayeret Mat\'Kal", "Soros",
    "Spetznaz", "Steak Knife", "subversives", "Ufologico Nazionale",
    "Undercover", "Verisign", "Waco", "Waihopai", "White House", "Whitewater",
    "wire transfer", "World Domination",

    # prism
    "1071", "1080H", "15kg", "1911", "1984", "1997", "22nd SAS",
    "2600 Magazine", "312", "3848", "3B2", "414", "50BMG", "707", "737",
    "747,777", "757", "767", "8182", "868", "888", "ABC", "ACC", "Active X",
    "ADIU", "advise", "advisors", "afsatcom", "AFSPC", "AHPCRC", "AIEWS",
    "AIMSX", "Aladdin", "Alica", "Alouette,executive", "AMEMB", "Amherst",
    "AMW", "ANC", "Anonymous", "AOL", "AOL TOS", "ARC", "Archives", "Area51",
    "argus", "Armani", "ARPA", "Artichoke", "ASIO", "ASIS", "ASLET", "Asset",
    "AT&T", "Atlas", "Audiotel", "Austin", "AVN", "B.D.M.,Sphinx", "Badger",
    "bank", "basement", "BBE", "BECCA", "Becker", "beef", "Bess", "bet",
    "Beyond Hope", "BfV", "BITNET", "black-bag", "Black-Ops", "Blackbird",
    "Blacklisted 411", "Blackmednet", "Blacknet", "Blowfish", "Blowpipe",
    "BMDO", "BND", "Bob", "BOP", "BOSS", "botux", "BRLO", "Broadside",
    "Bubba", "Bubba the Love Sponge", "bullion", "BVD", "Cable & Wireless",
    "CANSLO", "Cap-Stun", "Capricorn", "CATO", "CBM", "CBNRC", "CBOT", "CCC",
    "CCS", "CDA", "CDC", "cdi", "CESID", "CFC", "chaining", "chameleon man",
    "Chan", "Chelsea", "Chicago Posse", "Chobetsu", "chosen", "CID", "CIDA",
    "CIM", "CIO", "CIS", "CISE", "clone", "COCOT", "Coderpunks", "codes",
    "Cohiba", "Comirex", "Competitor", "Compsec", "Consul", "CONUS",
    "Cornflower", "Corporate Security", "COS", "COSMOS", "Covert Video",
    "Cowboy", "CQB", "CRA", "credit card", "cryptanalysis", "crypto-anarchy",
    "CSE", "csystems", "CTP", "CTU", "CUD", "cybercash", "Cypherpunks",
    "D-11", "Daisy", "data havens", "data-haven", "DATTA", "DCJFTF", "Dead",
    "DEADBEEF", "debugging", "Defcon", "defence Information Warfare", "Delta",
    "DERA", "DEVGRP", "DIA", "Dictionary", "Digicash", "DITSA", "DJC", "DOE",
    "Dolch", "DRA", "DREC", "DREO", "DSD", "DSS", "Duress", "DynCorp",
    "e-cash", "E.T.", "E911", "EADA", "EDI", "EG&G", "Egret", "Elvis",
    "Embassy", "enigma", "EOD", "ESN", "ETA", "eternity server", "EUB",
    "Event Security", "Exon Shell", "explicit", "Face", "fangs", "Fax",
    "Fax encryption", "FBIS", "FCIC", "FDM", "Fetish", "FINCEN", "finks",
    "Firewalls", "FIS", "fish", "FKS", "Flame", "Flashbangs", "FLETC",
    "Flintlock", "FLiR", "Flu", "FMS", "force", "Fort Meade", "Forte",
    "fraud", "freedom", "Freeh", "froglegs", "FSB", "FXR", "Gamma", "garbage",
    "Gatt", "GCHQ", "GEO", "GEODSS", "GEOS", "Geraldton", "GGL", "GIGN",
    "Gist", "Global", "Glock", "GOE", "Goodwin", "Gorelick", "gorilla",
    "Gorizont", "government", "GPMG", "grey Data", "grom", "GRU", "GSA",
    "GSG-9", "GSS", "Guppy", "H&K", "H.N.P.", "Hackers", "HAHO", "Halcon",
    "Halibut", "Harvard", "hate", "HIC", "High Security", "Hillal", "HoHoCon",
    "Hollyhock", "HPCC", "HRT", "HTCIA", "humint", "Hutsul", "IACIS", "ICE",
    "IDEA", "IDF", "IDP", "illuminati", "IMF", "Indigo",
    "industrial espionage", "industrial intelligence", "Infowar",
    "Ingram Mac-10", "INR", "INS", "interception", "Internet Underground",
    "Intiso", "Investigation", "Ionosphere", "IRIDF", "Iris", "IRS", "ISA",
    "ISACA", "ISI", "ISN", "ISS", "jack", "JANET", "Jasmine", "JAVA", "JICC",
    "JITEM", "Juile", "Juiliett Class Submarine", "Keyhole", "Kh-11",
    "Kilderkin", "Kilo Class", "Kiwi", "KLM", "l0ck", "LABLINK", "Lacrosse",
    "LEETAC", "Leitrim", "Lexis-Nexis", "LLC", "loch", "lock picking",
    "Locks", "Loin", "LRTS", "LUK", "Lynch", "M-14", "M.P.R.I.", "M72750",
    "Mace", "Macintosh Firewalls", "Macintosh Internet Security",
    "Macintosh Security", "mailbomb", "Mantis", "market", "Masuda",
    "Mavricks", "Mayfly", "MCI", "MD2", "MD4", "MD5", "MDA", "Medco", "mega",
    "Menwith", "Merlin", "Meta-hackers", "MI-17", "MI5", "Middleman",
    "Military", "Minox", "MIT", "MITM", "MOD", "MOIS", "mol", "Mole",
    "Morwenstow", "Mossberg", "MP5k", "MP5K-SD", "MSCJ", "MSEE", "MSNBC",
    "MSW", "MYK", "NACSI", "NATIA", "NATOA", "NAVWAN", "NAVWCWPNS", "NCCS",
    "NCSA", "Nerd", "niche", "NIJ", "Nike", "NIMA", "ninja", "nitrate",
    "nkvd", "NOCS", "NRC", "NRL", "NRO", "NSCT", "NSG", "NSP", "NSWC", "NTIS",
    "NTT", "NVD", "OAU", "Oratory", "orthodox", "Oscor", "OSS", "OTP",
    "package", "passwd", "Passwords", "Patel", "PBX", "PCS", "Peering", "PEM",
    "penrep", "Perl-RSA", "PFS", "PGP", "PGP 2.6.2.", "PGP 5.0i", "PGP 5.1",
    "PGP 5.53", "Phon-e", "Pine Gap", "pink noise", "Pixar", "PLA",
    "Planet-1", "Platform", "Playboy", "POCSAG", "Police", "Porno",
    "Pornstars", "PPP", "PPS", "president", "press-release", "Pretoria",
    "Priavacy", "primacord", "PRIME", "Propaganda", "PSAC", "Pseudonyms",
    "Psyops", "PTT", "r00t", "racal", "RAID", "rail gun", "Rand Corporation",
    "Rapid Reaction", "RCMP", "rebels", "Recce", "Red Cell", "redheads",
    "Reflection", "remailers", "ReMOB", "Reno", "replay", "Retinal Fetish",
    "RFI", "rhost", "rhosts", "RIT", "rogue", "Rolm", "Ronco", "RSA", "RSP",
    "RUOP", "RX-7", "S.A.I.C.", "S.E.T. Team", "S/Key", "SABC", "SACLANT",
    "SADF", "SADMS", "Salsa", "SAP", "SAR", "sardine", "SAS", "SASP", "SASR",
    "Satellite phones", "SBI", "SBIRS", "SBS", "SCIF", "screws", "Scully",
    "SEAL", "Sears Tower", "Secert Service", "Secure",
    "Secure Internet Connections", "secure shell", "Security Consulting",
    "Security Evaluation", "SEL", "SERT", "SETA", "Sex", "SGC", "SGDN", "SGI",
    "SHA", "SHAPE", "Shayet-13", "SHF", "SIG", "SIGDASYS", "SIGDEV",
    "sigvoice", "siliconpimp", "SIN", "SIRC", "SISDE", "SISMI", "Skytel",
    "SL-1", "SLI", "SLIP", "sneakers", "sniper", "snuffle", "SONANGOL",
    "SORO", "SORT", "Speakeasy", "speedbump", "spies", "Spoke",
    "spook keywords", "spook words", "Spyderco", "squib", "SRI", "ssa",
    "SSCI", "SSL", "stakeout", "Standford", "STARLAN", "Stego", "STEP",
    "Stephanie", "Steve Case", "Sugar Grove", "SUN", "Sundevil", "SURVIAC",
    "SUSLO", "SVR", "SWAT", "sweep", "sweeping", "SWS", "Talent",
    "TDM. SUKLO", "TDR", "TDYC", "Telex", "TELINT", "Templeton", "TEMPSET",
    "Terrorism Defensive Information", "Texas", "TEXTA. ELF", "THAAD", "the",
    "TIE", "Tie-fighter", "Time", "toad", "Tools", "top secret", "TRD",
    "Trump", "TRW", "TSCI", "TSCM", "TUSA", "TWA", "UDT", "UHF", "UKUSA",
    "unclassified", "UNCPCJ", "unix", "Unix Security", "UOP", "USACIL",
    "USAFA", "USCG", "USCODE", "USCOI", "USDOJ", "USP", "USSS", "UT/RUS",
    "utopia", "UTU", "UXO", "veggie", "VHF", "Vinnell", "VIP",
    "VIP Protection", "Virii", "virtual", "virus", "VLSI", "VNET",
    "Wackendude", "Wackenhutt", "WANK", "Weekly World News", "white noise",
    "William Gates", "WINGS", "WORM", "XS4ALL", "Yakima", "Yobie", "York",
    "Yukon", "Zen", "zip", "zone"
);

sub main
{
    printf "%s\n", join("\n", @spook_lines);
    return 0;
}

exit(main());
